volumes:
    langgraph-data:
        driver: local
    langgraph-data-mysql:
        driver: local
services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
    langgraph-postgres:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s

    langgraph-mysql:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: snowball2019
          MYSQL_DATABASE: langgraph_agent
          MYSQL_CHARSET: utf8mb4
          MYSQL_COLLATION: utf8mb4_unicode_ci
        volumes:
          - langgraph-data-mysql:/var/lib/mysql
        ports:
          - "3307:3306"

    langgraph-api:
        image: multi-agent_250116_6
        ports:
            - "8123:8000"
        depends_on:
            - langgraph-mysql
            - langgraph-redis
            - langgraph-postgres

        env_file:
            - .env
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            LANGSMITH_API_KEY: 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
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
