blank_issues_enabled: false
contact_links:
  - name: "Join the Community Group"
    about: Join the OpenManus community to discuss and get help from others
    url: https://github.com/FoundationAgents/OpenManus?tab=readme-ov-file#community-group
